[WIP]Speed up nftables via batching
crowdsecurity/cs-firewall-bouncer pull request #115
Opened 2022-01-31 08:35 UTC by sbs2001

Fixes https://github.com/crowdsecurity/cs-firewall-bouncer/issues/114 .

The `backend` interface has one more method `Commit` . This method is supposed to be called commit changes to the system, instead of relying `Add` and `Delete` methods. Only nftables currently follows this while other modes still work. 

`nftables` now instead of calling `Flush` for each `Add` or `Delete` does the following:

1. Compare decision stream with current state. Decisions are filtered off if their ip is already present (for new decision) or if ip is absent(decision is expired)
2. The filtered decisions are then batched into size of `200` (arbitary for now TBD) and `Flush` is called only once per batch

Benchmark TODO

2022-01-31 09:07 UTC, buixor requested changes
minor logging

2022-01-31 09:07 UTC, buixor commented on main.go
> +					log.Info("commiting expired decisions")
debug maybe ?

2022-01-31 09:07 UTC, buixor commented on main.go
> +					log.Info("commited expired decisions")
debug maybe ?

2022-01-31 09:07 UTC, buixor commented on main.go
> +					log.Info("commiting added decisions")
same x2

2022-01-31 19:33 UTC, jarppiko commented
Hi @sbs2001 is it necessary to remove the duplicates or is it an additional feature?

2022-02-01 11:34 UTC, sbs2001 commented
@jarppiko  nftables doesn't permit inserting duplicate IPs in single batch. It also errors if the item being inserted is already present in set.

2022-02-01 12:25 UTC, jarppiko commented
> @jarppiko nftables doesn't permit inserting duplicate IPs in single batch. It also errors if the item being inserted is already present in set.

This issue with importing duplicates has been partly fixed in `nftables`. Importing duplicates in a single batch does not cause errors with recent `nftables`, but if there is an existing rule, it does not update it. 

```
# cat ip-blocklist-duplicate-test.csv
value
1.116.1.107
1.116.1.22
1.116.1.239
1.116.101.225
1.116.102.149
1.116.1.107
1.116.101.225
1.116.101.225
# cscli decisions import  --reason "Test" --duration 3h -i ip-blocklist-duplicate-test.csv
INFO[01-02-2022 02:19:03 PM] 8 decisions successfully imported
#
```

And `var/log/crowdsec-firewall-bouncer.log` shows:  
```
time="01-02-2022 14:19:06" level=debug msg="adding '1.116.1.107' for '2h59m56.957743109s'"
time="01-02-2022 14:19:06" level=debug msg="adding '1.116.1.22' for '2h59m56.957741101s'"
time="01-02-2022 14:19:06" level=debug msg="adding '1.116.1.239' for '2h59m56.957740476s'"
time="01-02-2022 14:19:06" level=debug msg="adding '1.116.101.225' for '2h59m56.957740058s'"
time="01-02-2022 14:19:06" level=debug msg="adding '1.116.102.149' for '2h59m56.957739793s'"
time="01-02-2022 14:19:06" level=debug msg="adding '1.116.1.107' for '2h59m56.957739377s'"
time="01-02-2022 14:19:06" level=debug msg="adding '1.116.101.225' for '2h59m56.957739125s'"
time="01-02-2022 14:19:06" level=debug msg="adding '1.116.101.225' for '2h59m56.957738878s'"
time="01-02-2022 14:19:06" level=info msg="8 decisions added"
time="01-02-2022 14:19:06" level=debug msg="committed 8 decisions"
time="01-02-2022 14:19:06" level=info msg="committed 8 added decisions, 0 deleted decisions"
```

So the question is whether this import behavior is for upstream of crowdsec to fix.  What do you guys think?

2022-02-08 07:41 UTC, jarppiko commented on nftables.go
> +	}
Hi @sbs2001, now the logic is that the first decision will be saved, should it actually be the latest decision that gets a place in the normalized array?

2022-02-09 09:17 UTC, buixor commented on nftables.go
> +	for _, d := range decisions {
as we saw, I think we should keep the longest valid decision for now (until LAPI can help us with that)

2022-02-09 09:52 UTC, buixor approved these changes
lgtm

2022-02-09 10:39 UTC, buixor approved these changes
great

2022-02-09 10:43 UTC, merged